### ISSUE TITLE
The package may have incorrect main/module/exports specified in its package.json

### ISSUE THREAD

**Issue by cre8** [digitalbazaar/vc-status-list-context#8]
When using esbuild with angular, I get this message: `Failed to resolve entry for package "@digitalbazaar/vc-status-list-context". The package may have incorrect main/module/exports specified in its package.json.`

I already created a pull request to fix the file name in the package in #7 Assuming that the correct filename that is created when building it and not some wrong build configuration that messed it up

**Comment by davidlehn** [comment]
Fixed in 3.1.0.  Package was not including all the built files.  Pardon the delay, I missed this issue.  I think I might have included an extra file, but it should point at the correct esm one now.
